# themeing
font_size 15.0
tab_bar_edge top
include current-theme.conf

# new tab with cwd not default dir
map ctrl+shift+t new_tab_with_cwd

filter_notification all

# Allow remote control for tab title updates
allow_remote_control yes
