backend = "xrender";
animations = false;

# Prevent Thunar flashing
unredir-if-possible-exclude = [
  "class_g = 'Thunar'"
];

opacity-rule = [
  "100:class_g = 'Thunar'"
];

fade-exclude = [
  "class_g = 'Thunar'"
];
