-- Portable first-run KOReader preferences.
--
-- config/bin/install-koreader-config copies this file only when the live
-- settings.reader.lua does not exist. Keep device IDs, absolute paths, window
-- geometry, credentials, histories, caches, and recent-document state out.
return {
    ["back_in_filemanager"] = "default",
    ["back_in_reader"] = "previous_location",
    ["back_to_exit"] = "prompt",
    ["collate"] = "strcoll",
    ["color_rendering"] = true,
    ["copt_block_rendering_mode"] = 1,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_css"] = "./data/epub.css",
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_smooth_scaling"] = 0,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_font"] = "Noto Serif",
    ["cre_header_author"] = 0,
    ["cre_header_auto_refresh"] = 0,
    ["cre_header_battery"] = 1,
    ["cre_header_battery_percent"] = 1,
    ["cre_header_chapter_marks"] = 0,
    ["cre_header_clock"] = 0,
    ["cre_header_page_count"] = 0,
    ["cre_header_page_number"] = 0,
    ["cre_header_reading_percent"] = 0,
    ["cre_header_title"] = 1,
    ["default_highlight_action"] = "ask",
    ["dimension_units"] = "mm",
    ["document_metadata_folder"] = "dir",
    ["duration_format"] = "classic",
    ["exporter"] = {
        ["markdown"] = {
            ["formatting_options"] = {
                ["invert"] = "bold",
                ["lighten"] = "italic",
                ["strikeout"] = "strikethrough",
                ["underscore"] = "underline_markdownit",
            },
            ["highlight_formatting"] = true,
        },
    },
    ["night_mode"] = true,
    ["page_turns_disable_tap"] = true,
    ["page_turns_tap_zones"] = "default",
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["reader_footer_custom_text"] = "KOReader",
    ["reader_footer_custom_text_repetitions"] = "1",
    ["reader_footer_mode"] = 0,
    ["scroll_method"] = "classic",
    ["start_with"] = "filemanager",
    ["statistics"] = {
        ["calendar_browse_future_months"] = false,
        ["calendar_nb_book_spans"] = 3,
        ["calendar_show_histogram"] = true,
        ["calendar_start_day_of_week"] = 2,
        ["color"] = false,
        ["convert_to_db"] = true,
        ["freeze_finished_books"] = false,
        ["is_enabled"] = true,
        ["max_sec"] = 120,
        ["min_sec"] = 5,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub"] = true,
        ["footnote-inpage_fb2"] = true,
        ["inpage_footnote_font-size_smaller"] = true,
    },
    ["system_fonts"] = false,
    ["text_lang_fallback"] = "en-US",
    ["vocabulary_builder"] = {
        ["enabled"] = false,
        ["with_context"] = true,
    },
}
